services:
  marmeladka:
    build: .
    container_name: marmeladka
    restart: always
    depends_on:
      - postgres
    networks:
      - pgnet
    volumes:
      - ./database:/app/database
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    environment:
      - TZ=${TZ}
      - DATABASE_URL=${DATABASE_URL}
    command: sh -c "alembic upgrade head && python3 main.py"

  postgres:
    image: postgres:16
    container_name: marmeladka_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pgnet
      -
networks:
  pgnet:

volumes:
  db_data:
  telegram-bot-api-data: