"""update guild config

Revision ID: 00e8df0f93b2
Revises: 233b4ceb2929
Create Date: 2025-04-22 21:44:09.327207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e8df0f93b2'
down_revision: Union[str, None] = '233b4ceb2929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_config', sa.Column('private_category_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_config', 'private_category_id')
    # ### end Alembic commands ###
