"""private_voice_channel

Revision ID: 233b4ceb2929
Revises: 63d225466e75
Create Date: 2025-04-18 22:40:41.275284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233b4ceb2929'
down_revision: Union[str, None] = '63d225466e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_config', sa.Column('private_voice_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_config', 'private_voice_id')
    # ### end Alembic commands ###
