"""fix issues

Revision ID: 82a61992e39a
Revises: 00e8df0f93b2
Create Date: 2025-04-23 12:45:58.871244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a61992e39a'
down_revision: Union[str, None] = '00e8df0f93b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embed_config', sa.Column('description', sa.String(length=4096), nullable=True))
    op.drop_column('embed_config', 'descrition')
    op.alter_column('user_data', 'lang',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=7),
               existing_nullable=False,
               existing_server_default=sa.text("'en-EN'::character varying"))
    op.alter_column('user_data', 'biography',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_data', 'biography',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('user_data', 'lang',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("'en-EN'::character varying"))
    op.add_column('embed_config', sa.Column('descrition', sa.VARCHAR(length=4096), autoincrement=False, nullable=True))
    op.drop_column('embed_config', 'description')
    # ### end Alembic commands ###
